### PR TITLE
Added Boto3 support

### PR DESCRIPTION
**Pull request by sheats**
Was working on something else and decided to upgrade to boto3 first.  Let me know what you guys think.

### CODE REVIEW

**Comment by palewire** [comment]
Let me know when you think you've finished your work here.

**Comment by sheats** [comment]
I think I'm good now... not sure how much you guys care about the coveralls and QuantifiedCode checks.

**Comment by sheats** [comment]
Yes, seems to be -- more explanation here: https://github.com/spulec/moto/issues/348

**Comment by palewire** [comment]
Could we get some docstrings on those new s3 utils? And do they need to be a separate file? How broadly are they being used?

**Comment by sheats** [comment]
Sure, I can add some docstrings.  The two methods in s3_utils were just pulled out of duplicate code between the publish and unpublish management commands.  I can def put somewhere else.  

The get_s3_client one is used in tests along with those two commands -- I don't know how you guys want to handle configuration... currently it's grabbing environment variables and then letting settings override those.  Now that I think about it more I should probably make sure it's also honoring the ~/.aws/configure as well: http://boto3.readthedocs.io/en/latest/guide/configuration.html

**Comment by palewire** [comment]
What would you think of a base management command class shared by those two commands that includes the s3 methods?

**Comment by sheats** [comment]
Fine by me, I'll take it that way.

**Comment by palewire** [comment]
Great. That change and the docstrings and then I'll pull it down and see if I can break it. 

The only thing I really worry about is the odd "." bucket name bug that's given old boto so many problems through the years.

**Comment by sheats** [comment]
Yeah, not sure about that issue exactly -- I just never put "."s in my bucket names anymore cuz of ssl certs mostly.  

Just pushed the changes -- how I did the code in base_publish.py felt a little weird so please feel free to push back with other options.  Turned out that I used them all in the tests so didn't want to put them only in a management Command class.

**Comment by palewire** [comment]
It's a cosmetic thing, but putting the base class in named command file might result in it showing up for manage.py, something we don't want. Perhaps ``__init__.py`` is a good home for it?

**Comment by sheats** [comment]
I made those changes btw in case you didn't see that last commit.

**Comment by palewire** [comment]
I did see the changes but I haven't made the time yet. I'll try to give it a look today. Sorry for the delay.

**Comment by sheats** [comment]
No problem, just saw a comment on the issue ticket and wanted to make sure you saw it.

**Comment by palewire** [comment]
Alrighty. I've made some tweaks on my machine and merged you into the master branch. I'd like to test it a bit on some of my current implementations before releasing it on PyPI. Are there any particulars you can think of that upgraders will need to note? Or should it simply "just work?"

**Comment by sheats** [comment]
As far as I know it should just work... but I hadn't used the library before working on this so I'm not sure how much you should trust that :-)  It worked for me and I tried to do my best to simply swap out functionality and follow the existing flows.  I def would hope a couple experienced people get a chance to bang on it before pushing to PyPI.

**Comment by palewire** [comment]
K. There are some little things I'd like to check on, like GZIPing of the files and the batch deletion.

**Comment by palewire** [comment]
Alright. This seems to be working in my early tests. I'm going to prepare it to ship.

**Pull request merged**
