### PR TITLE
Added settings variable enabling adding '.gz' suffix to gzipped files

### PR DESCRIPTION
**Pull request by adogyf**

### CODE REVIEW

**Comment by palewire** [comment]
@adogyf, thanks for this pull request.

@joemfox and I have been wrestling with a gzip use case recently here at the Los Angeles Times.

I'm curious how you ended up proposing this solution. Where are you coming from, what bugs have you encountered, and why are you thinking this is the fix?

**Comment by adogyf** [comment]
Sorry for not providing a proper description. I want to serve baked site using nginx's [gzip_static](http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html#gzip_static) directive from ngx_http_gzip_static_module:
> The ngx_http_gzip_static_module module allows sending precompressed files with the “.gz” filename extension instead of regular files.

By using gzip_static nginx doesn't have to gzip each request, which reduces server load and provides faster response. Precompressing files and switching to static gzip allows nginx to know ahead of time the file size and send an appropriate Content-Length header.

**Comment by palewire** [comment]
So, do I understand you correctly that the problem with our current configuration is that while files can be gzipped during the "build" they do not have a .gz extension appended and therefore nginx's static extension doesn't detect they're already compressed and fails to serve them with the right headers?

**Comment by adogyf** [comment]
Yes, you are correct. To be specific, this pr will enable using bakery with [ngx_http_gunzip_module](http://nginx.org/en/docs/http/ngx_http_gunzip_module.html) or with 'gzip_static always;' directive (without checking if the client supports gzip), since there are no uncompressed files in the build directory anyway.

**Comment by palewire** [comment]
I'm open to this idea, but I'd like to see it implemented with less redundancy. Can you imagine a way the file names could be generated by a function or other means so we don't have to have these if statements all over the place?

**Comment by palewire** [comment]
I am closing this PR pending a response to my question above.

**Pull request closed without merging**
