### PR TITLE
Added BuildableMixin.create_request()

### PR DESCRIPTION
**Pull request by clintonb**
This method allows inheriting classes to customize the request used to generate output.

### CODE REVIEW

**Comment by clintonb** [comment]
@palewire please review/merge/release.

**Comment by palewire** [comment]
Totally open to this idea, but curious what your use case is.

**Comment by clintonb** [comment]
My site uses [wagtailmenus](https://pypi.python.org/pypi/wagtailmenus), and it makes use of `request.site`. At one point it also seemed to require `request.user`; however, that no longer seems to be the case.

**Comment by palewire** [comment]
Interesting. I've merged your change into master and shipped it to PyPI as v0.8.12. It should be available for you to upgrade to shortly. Thank you for this thoughtful improvement.

**Comment by clintonb** [comment]
Great. Thanks!

**Comment by palewire** [comment]
Glad you find django-bakery useful. It's always interesting to find out someone else is actually using it!

**Pull request merged**
